collections:
  - name: ansible.posix
    version: 1.5.4
  - name: community.general
    version: 8.5.0
  - name: ansible.windows
    version: 2.3.0
  - name: ansible.utils
    version: 4.1.0
  - name: community.windows
    version: 2.2.0
  - name: crowdstrike.falcon
    version: 4.5.0
